"""Keyword dictionaries for rule-based intent classification.

This module defines keyword sets for each intent category.
Extend these sets to improve classification accuracy before
upgrading to a model-based classifier.
"""

from app.services.rag.intent.intents import IntentType

# Keyword sets per intent. Order matters: more specific intents first.
INTENT_KEYWORDS: dict[IntentType, frozenset[str]] = {
    IntentType.DRUG_INTERACTION: frozenset({
        "같이",
        "함께",
        "병용",
        "상호작용",
        "금기",
        "병용금기",
        "동시에",
        "섞어",
        "혼용",
        "중복",
    }),
    IntentType.MY_SCHEDULE: frozenset({
        "내 약",
        "복용 시간",
        "먹을 시간",
        "언제 먹",
        "몇 시에",
        "남은 약",
        "복용 기록",
        "오늘 먹었",
        "약 먹었어",
        "복약 일정",
        "몇 개 남",
        "처방",
    }),
    IntentType.SUPPLEMENT_INFO: frozenset({
        "영양제",
        "비타민",
        "오메가",
        "유산균",
        "프로바이오틱",
        "미네랄",
        "칼슘",
        "마그네슘",
        "아연",
        "철분",
        "엽산",
        "보충제",
        "건강기능식품",
    }),
    IntentType.NEARBY_HOSPITAL: frozenset({
        "병원",
        "약국",
        "의원",
        "클리닉",
        "응급실",
        "근처",
        "주변",
        "가까운",
        "찾아줘",
        "어디",
    }),
    IntentType.WEATHER: frozenset({
        "날씨",
        "기온",
        "온도",
        "비",
        "눈",
        "맑음",
        "흐림",
        "습도",
        "미세먼지",
        "황사",
        "자외선",
        "기상",
    }),
    IntentType.MEDICATION_INFO: frozenset({
        "약",
        "부작용",
        "효능",
        "효과",
        "용법",
        "용량",
        "주의사항",
        "복용법",
        "성분",
        "약품",
        "의약품",
        "처방약",
        "진통제",
        "항생제",
        "소화제",
        "해열제",
        "혈압약",
        "당뇨약",
        "수면제",
        "안정제",
    }),
    IntentType.GENERAL_CHAT: frozenset({
        "안녕",
        "고마워",
        "감사",
        "잘 있어",
        "bye",
        "hello",
        "반가워",
        "좋아",
        "알겠어",
        "응",
        "네",
        "아니",
    }),
}

# Intents that require no keyword match (fallback order)
FALLBACK_INTENT = IntentType.OUT_OF_SCOPE
