"""Lifestyle guide model module.

This module defines the LifestyleGuide model for storing GPT-generated
medication-lifestyle interaction guides per profile.
"""

from enum import StrEnum

from tortoise import fields, models


class GuideCategory(StrEnum):
    """Lifestyle guide category enumeration.

    Represents the five health domains covered by the lifestyle guide.
    """

    DIET = "diet"
    SLEEP = "sleep"
    EXERCISE = "exercise"
    SYMPTOM = "symptom"
    INTERACTION = "interaction"


class LifestyleGuide(models.Model):
    """Lifestyle guide model for GPT-generated medication lifestyle advice.

    Stores the full JSON guide generated by GPT-4o-mini based on the user's
    active medications. Each guide is a snapshot tied to a specific set of
    medications at generation time.

    Attributes:
        id: Primary key UUID.
        profile: Foreign key to Profile model.
        content: Full GPT-generated guide as JSON (5-category structure).
        medication_snapshot: JSON snapshot of active medications at generation time.
        created_at: Guide generation timestamp.
    """

    id = fields.UUIDField(primary_key=True)
    profile = fields.ForeignKeyField(
        "models.Profile",
        related_name="lifestyle_guides",
        description="Guide owner profile",
    )

    # Full GPT response stored as JSON — 5-category structure
    content = fields.JSONField(description="GPT-generated guide content (5 categories)")

    # Snapshot of active medications at the time of generation
    # Used for medication change detection (future scope)
    medication_snapshot = fields.JSONField(
        description="Active medication list at guide generation time"
    )

    created_at = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "lifestyle_guides"
        indexes = (("profile_id", "created_at"),)
